config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server, at: "/cable"

  get 'sms/send_messages'
  resources :user

  patch 'update/:id', to: "user#update"

  get 'user/destroy'

  root 'pages#home'

  get 'dashboard', to: "dashboard#index"

  get 'dashboard/uploads'

  get 'account', to: "dashboard#account"

  post "/send_message", to: "sms#send_messages"

  post 'newphone', to: "available_phone_number#available_phones"

  post '/signin', to: 'sessions#create'

  post '/register', to: "registrations#create"

  post '/credoptions', to: "sms#twilio_api"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
	belongs_to :user, foreign_key: "user_id"
end

app/models/user.rb
class User < ApplicationRecord
  # EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
  PHONE_NUMBER_REGEX = /[\x2B]{1}\d{11}/
  validates :username, presence: true, uniqueness: true, :length => { :in => 3..20 }
  # validates :twilio_phone_number, format: PHONE_NUMBER_REGEX
  # validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  # validates_length_of :password, :in => 6..20, :on => :create
  
  has_secure_password



  has_many :posts
  has_many :lists
  has_many :images



  # checks if user has sufficient funds
	def balance_confirm
		if self.lists.count.to_d * 0.02.to_d <= self.balance
			return self.lists.pluck(:phone_number)
		else
			return nil
		end
	end

  # decrease balance - used often for sending messages
  def purchase(cost, success_numbers, failure_numbers)
    decrease = self.balance - cost.to_d
    self.update_attributes(balance: decrease)
    # if saved send balance information with reasons attached for balance change
    if self.save
      CostNotificationJob.perform_now(self.balance.to_s, self.id, success_numbers, failure_numbers)
    else
      p "record not saved: account not changed"
    end
  end


  private
  # add to balance amount

  def analyze_this
    byebug
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authentication
  	redirect_to root_path unless current_user
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_action :authentication
  def index
  	# @posts = @current_user.posts
  end

  def uploads
  end

  def account
  	@user = @current_user
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	# this is the sales page and Misc. controller
  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
	
	def create
		@user  = User.create(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to dashboard_path, flash: { success_sign_up: "Welcome! Here is your dashboard! :)"}
		else
			redirect_to root_path, flash: { error_sign_up: @user.errors.full_messages }
		end
	end

	private

	def user_params
		params.require(:user).permit(:username, :email, :password, :password_confirmation)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		user = User.find_by_email(params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			cookies.signed[:user_id] = user.id
			redirect_to dashboard_path, flash: { success: "You are signed in!" }
		else
			redirect_to root_path, flash: { session_error: "Sorry we didn't find you :(. Please try again."}
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "Come back soon! :)"
		redirect_to root
	end
	
end

app/controllers/sms_controller.rb
class SmsController < ApplicationController
	before_action :authentication

  def send_messages
    begin
      SendMessagesJob.perform_now(@current_user.twilio_api, 
                                  @current_user.twilio_secret, 
                                  @current_user,
                                  params[:body], params[:phones])
      
      # flash[:success] = "Messages being sent in the background"
    rescue Exception => e
      p e
    end
    respond_to do |format|
      format.html
      format.json { render json: "Very nice", status: 200}
    end
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
	before_action :authentication

	# change user attrubutes
	def update
		@current_user.update_attributes(update_params)
		if @current_user.save
			respond_to do |format|
				format.json { render json: { balance: current_user.balance.to_s, message: "the record was saved!", status: 200 } }
			end
		else
			respond_to do |format|
				format.html {}
				format.json { render json: { message: @current_user.errors.messages, status: 400 } }
			end
		end		
	end

	private

	def update_params
		sanitize_params
		update_balance
		params.require(:user).permit(:balance, :twilio_api, :twilio_secret)
	end

	def sanitize_params
		for key in params do
			if key[1] == ""
				params.delete(key[0])
			end
		end
		p params
	end

	def update_balance
		if params[:user][:balance]
			new_balance =  params[:user][:balance].to_d + @current_user.balance
			params[:user][:balance] = new_balance.to_s
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sms_helper.rb
module SmsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/dashboard/account.html.erb
<div class="inner-container">
	<%= render "partials/sidebar" %>
	<div id="twilio_settings">
		<div class="grey_border">
			<h4>Update your account</h4>
		</div>	
		<div class="settings_forms settings_blocks">
			<%= form_for(@user,  html: { id: "api_form"}, remote: true) do |u| %>
				<%= u.text_field :twilio_api, value: nil, placeholder: "Api number or SID" %>
				<%= u.text_field :twilio_secret, value: nil, placeholder: "Api secret key" %>
				<%= u.submit "change api credentials"%>
			<% end %>
			<%= form_for(@user, html: { id: "balance_form" }, remote: true) do |u| %>
				<%= u.number_field :balance, value: nil, placeholder: "add money" %>
				<%= u.submit "add to balance"%>
			<% end %>
		</div>
	</div>
</div>

app/views/dashboard/index.html.erb
	<div id="inner_cont" class="inner_container">
	<%= render "partials/sidebar" %>
	<!-- post -->
	<div id="post">
		<div class="post_header"><i class="ion-ios-compose-outline"></i><h5>Create Message</h5></div>
		<%= form_tag("/send_message",id: "submitMessage", remote: true) do  %>	
			<%= text_field_tag :body %>
			<%= text_field_tag :phones %>
			<div class="post_submit_div">
				<%= submit_tag "Send SMS", class: "submit_button" %>
			</div>
		<% end %>
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwilioService</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% flash.each do |key, msg| %>
  		<%= content_tag :div, msg, class: key%>
  	<% end %>  
      <%= render "partials/nav" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= form_tag("/signin", method: :post) do %>
	<%= email_field_tag :email %>
	<%= password_field_tag :password %>
	<%= submit_tag "Sign In" %>
<% end %>
<%= form_tag("/register", method: :post) do %>
	<%= text_field_tag "user[username]" %>
	<%= email_field_tag "user[email]" %>
	<%= password_field_tag "user[password]" %>
	<%= password_field_tag "user[password_confirmation]"%>
	<%= submit_tag "Sign Up" %>
<% end %>

app/views/partials/_nav.html.erb
<% if current_user != nil %>
	<nav id="nav">
		<div class="container">
			<div id="brand_div">
				<a href="/dashboard"><h1 id="brand_h1">SMSPRO</h1></a>
			</div>	
			<ul id="nav_list">
				<li><p id="balance">balance: <%= current_user.balance %></p></li>
				<li id="avatar_li"><div class="avatar_div"><p id="avatar_letter"><%= current_user.username[0]%></p></div></li>
			</ul>
		</div>
	</nav>
<% end %>

app/views/partials/_sidebar.html.erb
	<section id="side_bar">
		<ul id="sidebar_links" class="link_box">
			<li><%= link_to account_path do%>
				<i class="ion-ios-gear-outline"></i>
				<% end %>
			</li>
		</ul>
	</section>

app/views/sms/send_messages.html.erb
<h1>Sms#send_messages</h1>
<p>Find me in app/views/sms/send_messages.html.erb</p>

app/views/user/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

app/views/user/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>